management:
  endpoints:
    web:
      exposure:
        # Enable specific endpoints
        #include: health
        include: '*'
      #Custom base path instead of /actuator --> /manage
      #base-path: /manage
  #Enable health
  endpoint:
    health:
      show-details: always
      # Custom Health Group
      group:
        custom:
          include: diskSpace, ping
          show-details: always
          show-components: when_authorized

  # Enable info
  info:
    env:
      enabled: true
#Custom information about application
info:
  app:
    name: 'spring-boot-toom'
    description: 'Explaining about complete telemetry, observability and monitoring'
    version: '1'
  author: 'atquil'

logging:
  file:
    name: src/my-logs.log
  level:
    root: info





